### ISSUE TITLE
xgrad-cam理解

### ISSUE THREAD

**Issue by 131404060321** [Fu0511/XGrad-CAM#1]
你好，grad-cam的target_layer的权重是对应通道梯度的均值，而xgrad-cam的target_layer的权重则是 各通道feature map与对应梯度的乘积，然后各通道求和，最后除以target_layer各通道之和。请问这样理解是否正确？

**Comment by Fu0511** [comment]
@131404060321 您好，XGrad-CAM中，每个feature map的权重为该feature map与对应gradient map的响应乘积和，除以该feature map的响应和。

**Comment by 131404060321** [comment]
感谢回复。 再请问，以这样的方式设计权重有什么直觉上（非公式 : ) ）的解释吗？

**Comment by Fu0511** [comment]
目前只有数学的解释，并没有直觉上的解释。但这也是我们这项工作的意义所在。Grad-CAM将梯度平均作为每个feature map的权值，我们认为这是基于直觉的，而XGrad-CAM的权值定义是通过引入两个axiom，数学地推导得出的。

**Comment by 131404060321** [comment]
嗯嗯 蟹蟹！ 后续使用xgrad-cam过程中遇到问题再向您请教。
